import { config } from '../config'

export const MIN_NAME_SIZE = 2
export const MAX_NAME_SIZE = 15
export const VOTING_POWER_TO_PASS_LINKED_WEARABLES = config.get('VOTING_POWER_TO_PASS_LINKED_WEARABLES')
export const VOTING_POWER_TO_PASS_CATALYST = config.get('VOTING_POWER_TO_PASS_CATALYST')
export const VOTING_POWER_TO_PASS_BAN_NAME = config.get('VOTING_POWER_TO_PASS_BAN_NAME')
export const VOTING_POWER_TO_PASS_POI = config.get('VOTING_POWER_TO_PASS_POI')
export const VOTING_POWER_TO_PASS_POLL = config.get('VOTING_POWER_TO_PASS_POLL')
export const VOTING_POWER_TO_PASS_DRAFT = config.get('VOTING_POWER_TO_PASS_DRAFT')
export const VOTING_POWER_TO_PASS_GOVERNANCE = config.get('VOTING_POWER_TO_PASS_GOVERNANCE')
export const VOTING_POWER_TO_PASS_PITCH = config.get('VOTING_POWER_TO_PASS_PITCH')
export const VOTING_POWER_TO_PASS_TENDER = config.get('VOTING_POWER_TO_PASS_TENDER')
export const VOTING_POWER_TO_PASS_BID = config.get('VOTING_POWER_TO_PASS_BID')
export const SUBMISSION_THRESHOLD_DRAFT = config.get('SUBMISSION_THRESHOLD_DRAFT')
export const SUBMISSION_THRESHOLD_GOVERNANCE = config.get('SUBMISSION_THRESHOLD_GOVERNANCE')
export const SUBMISSION_THRESHOLD_POLL = config.get('SUBMISSION_THRESHOLD_POLL')
export const SUBMISSION_THRESHOLD_PITCH = config.get('SUBMISSION_THRESHOLD_PITCH')
export const SUBMISSION_THRESHOLD_TENDER = config.get('SUBMISSION_THRESHOLD_TENDER')
export const SUBMISSION_THRESHOLD_HIRING = config.get('SUBMISSION_THRESHOLD_HIRING')
export const SUBMISSION_THRESHOLD_GRANT = config.get('SUBMISSION_THRESHOLD_GRANT')
export const VOTING_POWER_TO_PASS_HIRING = config.get('VOTING_POWER_TO_PASS_HIRING')
